version: "3.8"

services:
    web:
        image: shekeriev/hw3-web
        deploy:
            replicas: 3
        ports:
            - 8080:80
        networks:
            - appnet
        depends_on:
            - db

    db:
        image: shekeriev/hw3-db
        networks:
            - appnet
        environment:
            MYSQL_ROOT_PASSWORD: "12345"

    prometheus:
          image: prom/prometheus:latest
          container_name: prometheus
          ports:
              - "9090:9090"
          volumes:
                - /etc/prometheus:/etc/prometheus
                - prometheus-data:/prometheus
          restart: unless-stopped
          command:
            - "--config.file=/etc/prometheus/prometheus.yml"

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        ports:
            - "3000:3000"
        volumes:
              - grafana-data:/var/lib/grafana
        restart: unless-stopped


volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

networks:
    appnet: