version: '3'
services:
    web:
        build: .
        image: hristodinev123/docker-web
        restart: always
        ports:
            - 80:8080
        networks:
            - app_network
        depends_on:
            - db

    db:
      build: .
      image: hristodinev123/docker-db
      restart: always
      environment:
            MYSQL_ROOT_PASSWORD: 12345
      ports:
      - '3306:3306'
      volumes:
      - db:/var/lib/mysql
      networks:
            - app_network
volumes:
  db:
    driver: local
networks: 
    app_network:

          